apiVersion: v1
kind: Pod
metadata:
  name: my-ip-app-sidecar-container
spec:
  containers:
  - name: nginx
    image: nginx:1.22.1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: "/var/log/nginx"
  - name: busybox-sharedlogs
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "count=0; while true; do count=$((count++)); echo ----------- $count -------------; cat /var/log/nginx/access.log; sleep 5; done"]
    volumeMounts:
    - name: shared-logs
      mountPath: "/var/log/nginx"

  volumes:
  - name: shared-logs
    emptyDir: {}

