apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv
spec:
  awsElasticBlockStore:
    volumeID: vol-0d151e59e77f4f031
    fsType: xfs
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
