apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-sa-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: k8s-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-sa-role
