apiVersion: v1
kind: Pod
metadata:
  name: my-ip-app-secrets
spec:
  containers:
  - name: ip-app
    image: harshajain/ip-app:1
    ports:
    - containerPort: 80
    env:
    - name: DB_URL
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: db_url
    - name: DB_UNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: db_username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: db_password


