apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: nginx-daemonset 
spec: 
    selector:
        matchLabels:
            app: my-nginx-daemonset
    template:
        metadata:
           labels: 
              app: my-nginx-daemonset
        spec:
           containers:
              - name: nginx 
                image: nginx:1.22.1 
                ports:
                  - containerPort: 80 
 

