apiVersion: apps/v1
kind: StatefulSet 
metadata:
    name: ip-app-statefulset 
spec: 
    replicas: 4
    selector:
        matchLabels:
            app: ip-app-sfs
    template:
        metadata:
           labels: 
              app: ip-app-sfs
        spec:
           containers:
              - name: ipapp 
                image: harshajain/ip-app:1
                ports:
                  - containerPort: 80 

--- 

apiVersion: v1
kind: Service
metadata:
    name: ip-app-headless-svc
spec: 
    clusterIP: None
    selector:
        app: ip-app-sfs
    ports:
       - name: http
         port: 30006     
         targetPort: 80
