apiVersion: apps/v1
kind: Deployment
metadata:
    name: ip-app-deployment 
spec: 
    replicas: 4
    selector:
        matchLabels:
            app: ip-app
    template:
        metadata:
           labels: 
              app: ip-app
        spec:
           containers:
              - name: ipapp 
                image: harshajain/ip-app:1
                ports:
                  - containerPort: 80 

---

apiVersion: v1
kind: Service
metadata:
    name: ip-app-cluster-ip
spec: 
    type: NodePort
    selector:
        app: ip-app
    ports:
       - name: http
         port: 30002     
         targetPort: 80
         nodePort: 30080